export const actionTypes = {
  REQUEST_EVENTS: 'REQUEST_EVENTS',
  REQUEST_EVENTS_SUCCSESS: 'REQUEST_EVENTS_SUCCSESS',
  REQUEST_EVENTS_FAIL: 'REQUEST_EVENTS_FAIL',

  EVENTS_READ_ALL_EVENTS: 'EVENTS_READ_ALL_EVENTS',
  EVENTS_DELETE_ALL_EVENTS: 'EVENTS_DELETE_ALL_EVENTS',
  EVENTS_ADD_EVENT: 'EVENTS_ADD_EVENT',
};
